/* Generated By:JavaCC: Do not edit this line. UrlParserConstants.java */
package io.mikael.poc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UrlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int URL_SCHEMA = 1;
  /** RegularExpression Id. */
  int WORD = 2;
  /** RegularExpression Id. */
  int INT = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<URL_SCHEMA>",
    "<WORD>",
    "<INT>",
    "\":\"",
    "\"//\"",
    "\"@\"",
    "\"/\"",
    "\"?\"",
    "\"#\"",
    "\"/a_fragment\"",
    "\"=\"",
    "\"&\"",
  };

}
