/* Generated By:JavaCC: Do not edit this line. CurtaParserTreeConstants.java Version 5.0 */
package nl.bigo.curta;

public interface CurtaParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTRETURN = 2;
  public int JJTASSIGN = 3;
  public int JJTOR = 4;
  public int JJTAND = 5;
  public int JJTBOR = 6;
  public int JJTBXOR = 7;
  public int JJTBAND = 8;
  public int JJTEQ = 9;
  public int JJTNEQ = 10;
  public int JJTGTE = 11;
  public int JJTLTE = 12;
  public int JJTGT = 13;
  public int JJTLT = 14;
  public int JJTSLSHIFT = 15;
  public int JJTURSHIFT = 16;
  public int JJTSRSHIFT = 17;
  public int JJTADD = 18;
  public int JJTSUB = 19;
  public int JJTMUL = 20;
  public int JJTDIV = 21;
  public int JJTMOD = 22;
  public int JJTUNARYSUB = 23;
  public int JJTUNARYADD = 24;
  public int JJTNOT = 25;
  public int JJTBNOT = 26;
  public int JJTPOW = 27;
  public int JJTFUNCTION = 28;
  public int JJTNUM = 29;
  public int JJTNULL = 30;
  public int JJTID = 31;
  public int JJTBOOL = 32;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Return",
    "Assign",
    "Or",
    "And",
    "BOr",
    "BXOr",
    "BAnd",
    "Eq",
    "NEq",
    "GTE",
    "LTE",
    "GT",
    "LT",
    "SLShift",
    "URShift",
    "SRShift",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Mod",
    "UnarySub",
    "UnaryAdd",
    "Not",
    "BNot",
    "Pow",
    "Function",
    "Num",
    "Null",
    "Id",
    "Bool",
  };
}
/* JavaCC - OriginalChecksum=30d37bf1de0271969a80ee6110d8df82 (do not edit this line) */
