/* Generated By:JavaCC: Do not edit this line. testConstants.java */
package html.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface testConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HTML = 6;
  /** RegularExpression Id. */
  int HEAD = 7;
  /** RegularExpression Id. */
  int BODY = 8;
  /** RegularExpression Id. */
  int ST_TABLE = 9;
  /** RegularExpression Id. */
  int ND_TABLE = 10;
  /** RegularExpression Id. */
  int ST_TITLE = 11;
  /** RegularExpression Id. */
  int ND_TITLE = 12;
  /** RegularExpression Id. */
  int ST_P = 13;
  /** RegularExpression Id. */
  int ND_P = 14;
  /** RegularExpression Id. */
  int ST_A = 15;
  /** RegularExpression Id. */
  int ND_A = 16;
  /** RegularExpression Id. */
  int ST_IMG = 17;
  /** RegularExpression Id. */
  int ST_TD = 18;
  /** RegularExpression Id. */
  int ND_TD = 19;
  /** RegularExpression Id. */
  int ST_TR = 20;
  /** RegularExpression Id. */
  int ND_TR = 21;
  /** RegularExpression Id. */
  int ST_DIV = 22;
  /** RegularExpression Id. */
  int ND_DIV = 23;
  /** RegularExpression Id. */
  int ST_H1 = 24;
  /** RegularExpression Id. */
  int ND_H1 = 25;
  /** RegularExpression Id. */
  int ST_H2 = 26;
  /** RegularExpression Id. */
  int ND_H2 = 27;
  /** RegularExpression Id. */
  int ST_H3 = 28;
  /** RegularExpression Id. */
  int ND_H3 = 29;
  /** RegularExpression Id. */
  int ST_H4 = 30;
  /** RegularExpression Id. */
  int ND_H4 = 31;
  /** RegularExpression Id. */
  int ST_H5 = 32;
  /** RegularExpression Id. */
  int ND_H5 = 33;
  /** RegularExpression Id. */
  int ST_H6 = 34;
  /** RegularExpression Id. */
  int ND_H6 = 35;
  /** RegularExpression Id. */
  int ST_SPAN = 36;
  /** RegularExpression Id. */
  int ND_SPAN = 37;
  /** RegularExpression Id. */
  int ST_DETAILS = 38;
  /** RegularExpression Id. */
  int ND_DETAILS = 39;
  /** RegularExpression Id. */
  int ST_SUMMARY = 40;
  /** RegularExpression Id. */
  int ND_SUMMARY = 41;
  /** RegularExpression Id. */
  int ST_OL = 42;
  /** RegularExpression Id. */
  int ND_OL = 43;
  /** RegularExpression Id. */
  int ST_LI = 44;
  /** RegularExpression Id. */
  int ND_LI = 45;
  /** RegularExpression Id. */
  int ST_BUTTON = 46;
  /** RegularExpression Id. */
  int ND_BUTTON = 47;
  /** RegularExpression Id. */
  int ST = 48;
  /** RegularExpression Id. */
  int ND = 49;
  /** RegularExpression Id. */
  int STRING = 50;
  /** RegularExpression Id. */
  int WIDTH = 51;
  /** RegularExpression Id. */
  int HEIGHT = 52;
  /** RegularExpression Id. */
  int ALT = 53;
  /** RegularExpression Id. */
  int CLASS = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"HTML\"",
    "\"HEAD\"",
    "\"BODY\"",
    "\"<TABLE>\"",
    "\"</TABLE>\"",
    "\"<TITLE>\"",
    "\"</TITLE>\"",
    "\"<P>\"",
    "\"</P>\"",
    "<ST_A>",
    "\"</A>\"",
    "<ST_IMG>",
    "\"<TR>\"",
    "\"</TR>\"",
    "\"<TD>\"",
    "\"</TD>\"",
    "<ST_DIV>",
    "\"</DIV>\"",
    "\"<H1>\"",
    "\"</H1>\"",
    "\"<H2>\"",
    "\"</H2>\"",
    "\"<H3>\"",
    "\"</H3>\"",
    "\"<H4>\"",
    "\"</H4>\"",
    "\"<H5>\"",
    "\"</H5>\"",
    "\"<H6>\"",
    "\"</H6>\"",
    "\"<SPAN>\"",
    "\"</SPAN>\"",
    "\"<details>\"",
    "\"</details>\"",
    "\"<summary>\"",
    "\"</summary>\"",
    "\"<OL>\"",
    "\"</OL>\"",
    "\"<LI>\"",
    "\"</LI>\"",
    "\"<BUTTON>\"",
    "\"</BUTTON>\"",
    "\"<\"",
    "\">\"",
    "<STRING>",
    "<WIDTH>",
    "<HEIGHT>",
    "<ALT>",
    "<CLASS>",
    "\"lang=\\\"\"",
    "\"\\\"\"",
    "\"/\"",
  };

}
